<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		
		<UserSecretsId>846556a4-4b5f-417b-bd77-fa4a5fcec0b3</UserSecretsId>

		<!-- Hikvision SDK is 64-bit -->
		<PlatformTarget>x64</PlatformTarget>
		<Prefer32Bit>false</Prefer32Bit>
		<AssemblyName>HikvisionANPR</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<!-- Copy Hikvision SDK files to the application's output folder -->
	<ItemGroup>
		<None Include="HikvisionSDK\**\*" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Hikvision\" />
	</ItemGroup>

</Project>